//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampaignsManagement.Services.Api.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLicense
    {
        public int LicenseId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    }
}
