//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampaignsManagement.Services.Api.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublishedCampaign
    {
        public int PublishId { get; set; }
        public int CampaignId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public int PublishedBy { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
    
        public virtual CampaignUser CampaignUser { get; set; }
        public virtual Group Group { get; set; }
    }
}
