//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampaignsManagement.Services.Api.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCampaign
    {
        public int UserCampaignId { get; set; }
        public int CampaignId { get; set; }
        public int UserId { get; set; }
        public int GroupId { get; set; }
        public Nullable<System.DateTime> ViewDate { get; set; }
        public Nullable<bool> VideoWatched { get; set; }
        public Nullable<System.TimeSpan> VideoTime { get; set; }
        public Nullable<System.DateTime> VideoDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
