//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampaignsManagement.Services.Api.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoId { get; set; }
        public string VideoName { get; set; }
        public string VideoPath { get; set; }
        public string FileName { get; set; }
        public Nullable<decimal> VideoLength { get; set; }
        public bool Active { get; set; }
    }
}
